# Generated by Django 2.1 on 2018-08-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='description',
            field=models.CharField(default='Add description here...', max_length=1000),
        ),
    ]
