# Generated by Django 2.1 on 2019-01-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0005_art_shopurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="art",
            name="image_logo",
        ),
        migrations.AddField(
            model_name="art",
            name="file_frame",
            field=models.FileField(default="default", upload_to=""),
            preserve_default=False,
        ),
    ]
